export class WorkspaceError extends Error {
  readonly code: string;
  readonly status: number;

  constructor(message: string, code: string, status: number = 400) {
    super(message);
    this.name = "WorkspaceError";
    this.code = code;
    this.status = status;
  }
}

export const WorkspaceErrorCode = {
  WORKSPACE_ROOT_NOT_FOUND: "WORKSPACE_ROOT_NOT_FOUND",
  PATH_OUTSIDE_WORKSPACE: "PATH_OUTSIDE_WORKSPACE",
  SENSITIVE_PATH_DENIED: "SENSITIVE_PATH_DENIED",
  FILE_NOT_FOUND: "FILE_NOT_FOUND",
  SYMLINK_OUTSIDE_WORKSPACE: "SYMLINK_OUTSIDE_WORKSPACE",
  NOT_A_FILE: "NOT_A_FILE",
  NOT_A_DIRECTORY: "NOT_A_DIRECTORY",
  PATH_IS_DIRECTORY: "PATH_IS_DIRECTORY",
  DIRECTORY_NOT_FOUND: "DIRECTORY_NOT_FOUND",
  PARENT_NOT_DIRECTORY: "PARENT_NOT_DIRECTORY",
  FILE_ALREADY_EXISTS: "FILE_ALREADY_EXISTS",
  TARGET_NOT_FOUND: "TARGET_NOT_FOUND",
  ANCHOR_NOT_FOUND: "ANCHOR_NOT_FOUND",
  AMBIGUOUS_REPLACEMENT: "AMBIGUOUS_REPLACEMENT",
  INVALID_LINE_RANGE: "INVALID_LINE_RANGE",
  INVALID_ARGUMENT: "INVALID_ARGUMENT",
  UNSUPPORTED_BINARY_FILE: "UNSUPPORTED_BINARY_FILE",
  UNSUPPORTED_TEXT_ENCODING: "UNSUPPORTED_TEXT_ENCODING",
  SEARCH_FAILED: "SEARCH_FAILED",
} as const;

export type WorkspaceErrorCode =
  (typeof WorkspaceErrorCode)[keyof typeof WorkspaceErrorCode];
