/**
 * 构造开箱即用的专业单代码仓维护指导语模版
 */
export function buildCodeRepoPrompt(data: any): string {
  const repo = data.repo || "";
  const repoPath = data.path || (repo ? `/srv/workspace/${repo}` : "/srv/workspace");
  const branch = data.branch || "master";
  const from = data.from || "initial";
  const to = data.to || "";
  const commitCount = data.commitCount ?? 0;
  const changedFilesCount = data.changedFilesCount ?? 0;
  const commitsSummary = data.commitsSummary || "无新增提交";
  const diffSummary = data.diffSummary || "无文件变动";

  const lines = [
    `# 知识维护单仓任务指导`,
    ``,
    `请针对目标仓库 ${repo} 执行单仓全生命周期知识维护与核验闭环。`,
    ``,
    `## 任务背景与基线`,
    ``,
    `- 目标仓库：${repo}`,
    `- 工作区绝对路径：${repoPath}`,
    `- 目标分支：${branch}`,
    `- 前置检查点：${from}`,
    `- 目标检查点：${to}`,
    `- 待核验提交统计：新增提交共 ${commitCount} 个，涉及 ${changedFilesCount} 个文件变动。`,
    ``,
    `### 提交清单摘要`,
    `\`\`\``,
    commitsSummary,
    `\`\`\``,
    ``,
    `### 变动文件统计`,
    `\`\`\``,
    diffSummary,
    `\`\`\``,
    ``,
    `## 技能规范与参考`,
    ``,
    `请挂载并严格遵循 skills/knowledge-maintenance-orchestrator/SKILL.md 与 skills/project-knowledge-maintainer 技能规范。`,
    ``,
    `## 工作区拓扑与绝对路径清单`,
    ``,
    `- 目标仓库：${repoPath}`,
    `- 兄弟代码仓：/srv/workspace/<sibling-repo>`,
    `- 系统知识仓：/srv/workspace/system-knowledge`,
    `- 动作参数统一使用绝对路径。`,
    ``,
    `## 六大分类落盘规范与命名公式`,
    ``,
    `- 知识文档存储目录：${repoPath}/docs/knowledge/<category>/`,
    `- 文件命名公式：<category>-<topic>.md（小写英文与连字符）`,
    `- 根目录导航文件：${repoPath}/docs/knowledge/ 根目录下必须具备 index.md 与 overview.md。`,
    `- 六大分类专项关注与红线约束：`,
    `  - flow 类别：业务端到端主流程、关键分支、关联键流转与失败传播；`,
    `  - interface 类别：对外 HTTP/RPC 接口、MQ 消息事件与调度任务的契约定义、入出参及失败返回；`,
    `  - rule 类别：跨流程公共规则、校验约束、多商户隔离策略与计算公式；`,
    `  - module 类别：核心模块划分、分层职责与内部调用拓扑；`,
    `  - data 类别（红线约束）：数据库事实源在 /srv/workspace/system-knowledge。优先查阅系统知识仓的 db-map.md 与 ddl/data-ddl-{schema}.md；本仓仅建 data/data-databases.md 轻量引用索引，注明所涉表域与数据源，无则标缺口。严禁在代码仓自身文档中复制粘贴表结构或建表脚本；`,
    `  - runbook 类别：排障手册、高频错误码、运维配置与故障自愈流程；`,
    ``,
    `## 更新门槛与失效四问判定`,
    ``,
    `- 失效四问判定（与技能规范定义一致）：`,
    `  - 行为：文档记载的流程、分支、状态、顺序、失败传播是否变化？`,
    `  - 契约：文档记载的接口出入参、事件、队列、配置键语义是否变化？`,
    `  - 定位：文档给出的文件、类、方法是否改名或移动？（行号漂移不算）`,
    `  - 缺失：是否新增了该文档主题内读者需要的事实（新入口、新分支、新失败路径、新公共规则）？`,
    `- 若四问均为“否”（仅为代码重构或优化，业务未变），严禁改动文档，直接判定为无需更新（no_change_needed）。`,
    ``,
    `## 特权受控工具速查与自省指令`,
    ``,
    `- 依托 ActionDock 特权环境（--profile skm），支持 ad info / ad list / ad describe 远端自省：`,
    `  - ad info --profile skm：查看远端挂载的所有工具包、动作与规程概览；`,
    `  - ad list --profile skm：列出远端所有可用动作清单及其功能描述；`,
    `  - ad describe <action> --profile skm：查询具体动作的完整描述、模式定义与传参示例。`,
    `- 常用动作绝对路径调用示例：`,
    `  - 全文检索：ad run workspace/search.rg --profile skm -- pattern="<keyword>" paths.0="${repoPath}"`,
    `  - 分段直读：ad run workspace/files.read --profile skm -- path="${repoPath}/<file>" startLine:=1 maxLines:=2000`,
    `  - 局部编辑：ad run workspace/files.edit --profile skm -- path="${repoPath}/<file>" targetContent="<old>" replacementContent="<new>"（复杂多行推荐使用 --input-file 传递 JSON 文件入参避开转义）；`,
    `  - 安全写入：ad run workspace/files.write --profile skm -- path="${repoPath}/<file>" content="<content>"（大文件或复杂 Markdown 推荐使用 --input-file 传递 JSON 文件入参）；`,
    `  - 目录浏览：ad run workspace/files.list --profile skm -- path="${repoPath}/<dir>" depth:=1`,
    `  - 终端命令与改动回滚：ad run workspace/bash.exec --profile skm -- command="git restore ." cwd="${repoPath}"`,
    ``,
    `## 断链自检、工作区审查与就地修复门禁（铁律）`,
    ``,
    `- 文档新建或修改后必须执行断链校验：`,
    `  - ad run workspace/links.verify --profile skm -- path="${repoPath}"`,
    `- 若有断链（brokenCount > 0）必须使用 files.edit 立即就地修复至零断链（brokenCount === 0）方可汇报。`,
    `- 提交前必须执行工作区状态审查，确认修改完全收敛于文档目录：`,
    `  - 查看状态：ad run workspace/bash.exec --profile skm -- command="git status" cwd="${repoPath}"`,
    `  - 核验差异：ad run workspace/bash.exec --profile skm -- command="git diff" cwd="${repoPath}"`,
    `  - 误改回滚：若误触业务源码立即执行 ad run workspace/bash.exec --profile skm -- command="git restore ." cwd="${repoPath}" 回滚丢弃修改。`,
    ``,
    `## 最终交付与推进检查点水位（绝对交付标志）`,
    ``,
    `- 有文档改动时调用：`,
    `  - ad run maintenance/maintenance.publish --profile skm -- path="${repoPath}" message="docs: update knowledge for ${repo}"`,
    `- 无论文档是否修改，最后必须调用检查点推进动作（绝对交付标志）：`,
    `  - 文档有更新：ad run maintenance/maintenance.complete --profile skm -- path="${repoPath}" commit="${to}" actionTaken="docs_updated" summary="<更新说明>"`,
    `  - 文档无需更新：ad run maintenance/maintenance.complete --profile skm -- path="${repoPath}" commit="${to}" actionTaken="no_change_needed" summary="<代码重构或优化，业务未变，无需更新文档>"`,
  ];

  return lines.join("\n");
}
