/**
 * 构造针对系统知识库的全局聚合维护指导语模版
 */
export function buildSystemKnowledgePrompt(data: any): string {
  const repo = data.repo || "system-knowledge";
  const repoPath = data.path || "/srv/workspace/system-knowledge";
  const branch = data.branch || "master";
  const from = data.from || "initial";
  const to = data.to || "";
  const commitCount = data.commitCount ?? 0;
  const changedFilesCount = data.changedFilesCount ?? 0;
  const commitsSummary = data.commitsSummary || "无新增提交";
  const diffSummary = data.diffSummary || "无文件变动";
  const codePhaseSummary = data.codePhaseSummary || "无前序代码仓巡检记录";

  const lines = [
    `# 系统知识库全局聚合维护指导`,
    ``,
    `请针对系统知识库 ${repo}（${repoPath}）执行跨仓领域聚合、新领域发现、端到端流程与全局资产核验闭环。`,
    ``,
    `## 任务背景与基线`,
    ``,
    `- 目标系统仓：${repo}`,
    `- 工作区绝对路径：${repoPath}`,
    `- 目标分支：${branch}`,
    `- 前置检查点：${from}`,
    `- 目标检查点：${to}`,
    `- 待核验提交统计：本仓新增提交共 ${commitCount} 个，涉及 ${changedFilesCount} 个文件变动。`,
    ``,
    `### 前序代码仓巡检摘要`,
    `\`\`\``,
    codePhaseSummary,
    `\`\`\``,
    ``,
    `### 本仓提交清单摘要`,
    `\`\`\``,
    commitsSummary,
    `\`\`\``,
    ``,
    `### 本仓变动文件统计`,
    `\`\`\``,
    diffSummary,
    `\`\`\``,
    ``,
    `## 技能规范与参考`,
    ``,
    `请挂载并严格遵循 skills/knowledge-maintenance-orchestrator/SKILL.md 与 skills/project-knowledge-maintainer 技能规范（重点参考 references/system-knowledge-workflow.md、references/cross-repository.md、references/layout.md 与 references/maintenance.md）。`,
    ``,
    `## 主智能体统筹定位与子代理协同架构`,
    ``,
    `- 主智能体角色定位：作为系统层知识维护总控中枢，主智能体负责统筹决策、自主规划、子代理调度委派与最终门禁验收，绝不亲自盲目编辑文件。全流程严格遵循全自动自闭环执行铁律，严禁挂起终端等待人工干预。`,
    `- 专业子代理协同分工：`,
    `  - 跨仓契约与领域影响分析子代理：深入工作区兄弟仓提取接口、事件与数据库客观证据，依据三路决策树判定并起草演进方案；`,
    `  - 新领域初始化子代理：负责开辟全新领域目录骨架、一次建齐全部六大分类目录，并同步维护系统根目录索引；`,
    `  - 跨仓主流程子代理：负责横向整合兄弟仓交互行为，起草与更新跨仓端到端主流程；`,
    `  - 接口与数据模型子代理：负责核对跨服务契约交接、全局数据库映射与结构快照。`,
    ``,
    `## 系统知识库目录结构与落盘规范`,
    ``,
    `- 系统层根目录固定资产：`,
    `  - index.md：系统总索引（业务领域清单 + 代码仓归属对照表）；`,
    `  - db-map.md：全局数据库与业务领域映射表（生产与测试库名、业务领域、域名、DDL 快照反查）；`,
    `  - ddl/：生产数据库结构快照（data-ddl-{schema}.md，包含字段语义补丁节）；`,
    `- 业务领域一级子目录落盘规范：`,
    `  - 存储目录：${repoPath}/{业务领域中文名}/（例如 订单履约/、跨境结算/）；`,
    `  - 领域导航文件：每个领域根目录下必须具备 index.md 与 overview.md；`,
    `  - 统一六大类别目录：每个业务领域内部必须具备全部六大分类单数目录（flow/、module/、rule/、interface/、data/、runbook/）；`,
    `  - 文件命名公式：<category>-<topic>.md（小写英文与连字符）；`,
    ``,
    `## 第一阶段：全景事实探索与自主推导决策`,
    ``,
    `- 全自动自闭环执行铁律（严禁中断流水线）：`,
    `  - 流水线为无人值守全自动作业，严禁停下来等待人工确认或决策；`,
    `  - 严禁在终端向用户提问、索求确认或等待输入，禁止出现需要人工确认等阻塞交互话术；`,
    `  - 主智能体基于客观代码事实自主决策、自主规划，直接推进后续阶段。`,
    `- 全景资产反查与主动探索门禁（防偷懒铁律）：`,
    `  - 严禁仅凭增量提交未触碰业务源码（例如仅升级依赖或修改构建配置）便草率判定为无需更新；`,
    `  - 系统知识库承担全局资产治理职责，必须横向扫描工作区平铺的全部代码仓（/srv/workspace/*），对照系统总索引 index.md 检查是否存在未纳管的物理代码仓；`,
    `  - 调阅各代码仓前序巡检生成的单仓文档，检查是否存在未沉淀至系统层的跨仓主流程或接口契约；`,
    `  - 检查存量业务领域是否缺失六大分类目录或导航文件；`,
    `  - 检查全局数据库映射 db-map.md 与 DDL 快照 ddl/ 是否完备。`,
    `- 自动化事实证据提取：委派跨仓契约与领域影响分析子代理，横向扫描工作区兄弟仓（/srv/workspace/*）提取证据，杜绝凭空臆测：`,
    `  - 源码接口与路由：检索 Controller、路由定义、RPC 契约与对外暴露服务；`,
    `  - 消息事件：检索 MQ 主题生产者与消费者、消息载荷与队列绑定；`,
    `  - 数据库资产：检索 Flyway 迁移脚本、DDL 变更与持久化实体模型。`,
    `- 三路自主决策树判定：`,
    `  - 路径一（开辟新领域）：发现未纳管代码仓或全新业务线契约时，执行业务领域识别与目录初始化三步法：`,
    `    - 调阅根目录 index.md，获取已登记的业务领域清单与代码仓归属对照表；`,
    `    - 扫描工作区（/srv/workspace/*）中所有已纳管代码仓，比对识别是否存在未被任何业务领域纳管的新增代码仓；`,
    `    - 研判业务归属并执行开辟全新领域：在系统知识库根目录下建立新领域中文目录，按统一规范一次建齐全部六大分类目录及基础导航，并在 index.md 与 db-map.md 补齐映射。`,
    `  - 路径二（更新已有领域）：核验跨仓影响是否破坏存量有效性，或存量业务领域存在知识缺漏，若触及以下任一维度则更新对应领域文档：`,
    `    - 存量系统知识库有效性与更新判定门禁（失效判定）：排查存量文档是否与代码现状脱节；`,
    `    - 行为层：跨仓端到端主流程、调用顺序或失败补偿机制是否发生变化；`,
    `    - 契约层：对外 HTTP/RPC 接口、MQ 消息事件或调度任务跨服务交接是否发生变化；`,
    `    - 数据层：是否有数据库表结构变动或全局状态流转调整（核对 db-map.md 与 ddl/ 快照）；`,
    `    - 存量补全：存量领域缺少六大分类目录、导航文件或未整合前序单仓巡检新资产；`,
    `  - 路径三（无需更新 - 高门槛严格兜底）：仅在完成上述全景主动探索、确证所有物理仓均已登记纳管、存量业务领域六大分类目录完整健全、跨仓端到端主流程与全局数据库资产无任何缺漏，且前序提交经核验确未破坏对外契约与跨仓流程时，方可审慎判定为无需更新（no_change_needed）。`,
    `- 自主方案规划（直接闭环，不挂起终端）：`,
    `  - 主智能体自主记录演进方案与子代理委派计划，明确判定依据与拟变更资产清单；`,
    `  - 自主方案记录直接作为内部执行基准并流转至后续写入阶段，最终沉淀于交付报告，绝不输出等待用户确认等阻塞语。`,
    ``,
    `## 第二阶段：受控写入与专业子代理委派`,
    ``,
    `- 方案规划完成后，主智能体委派专项子代理深入执行受控写入：`,
    `  - 开辟新领域场景：委派新领域初始化子代理，一次建齐六大分类目录与基础索引；`,
    `  - 跨仓主流程编排场景：委派跨仓主流程子代理，依循统一规范起草 flow/ 文档；`,
    `  - 契约与模型同步场景：委派接口与数据模型子代理，同步 interface/ 契约、db-map.md 与 ddl/ 快照；`,
    `- 主智能体全程把控写入边界，严禁跨领域串碰。`,
    `- 若经过全景主动探索与严格核验判定为无需更新，则直接跳过本阶段。`,
    ``,
    `## 第三阶段：零断链验收与推进检查点水位`,
    ``,
    `- 特权受控工具速查与自省指令（--profile skm）：`,
    `  - ad info / ad list / ad describe --profile skm：远端自省可用工具包、动作清单与参数规格；`,
    `  - 全文检索：ad run workspace/search.rg --profile skm -- pattern="<keyword>" paths.0="${repoPath}"`,
    `  - 分段直读：ad run workspace/files.read --profile skm -- path="${repoPath}/<file>" startLine:=1 maxLines:=2000`,
    `  - 局部编辑：ad run workspace/files.edit --profile skm -- path="${repoPath}/<file>" targetContent="<old>" replacementContent="<new>"（复杂多行推荐使用 --input-file 传递 JSON 文件入参避开转义）；`,
    `  - 安全写入：ad run workspace/files.write --profile skm -- path="${repoPath}/<file>" content="<content>"（大文件或复杂 Markdown 推荐使用 --input-file 传递 JSON 文件入参）；`,
    `  - 目录浏览：ad run workspace/files.list --profile skm -- path="${repoPath}" depth:=2`,
    `  - 终端审查：ad run workspace/bash.exec --profile skm -- command="git status" cwd="${repoPath}"`,
    `- 断链自检自愈门禁（铁律）：`,
    `  - 系统知识库修改完成后，必须在系统知识库根目录运行断链校验：`,
    `    - ad run workspace/links.verify --profile skm -- path="${repoPath}"`,
    `  - 若有断链（brokenCount > 0）必须就地修复至零断链（brokenCount === 0）方可放行。`,
    `- 统一发布与推进检查点水位（绝对交付标志）：`,
    `  - 系统知识库修改必须直接提交并推送到 master 分支：`,
    `    - 有文档改动时调用：ad run maintenance/maintenance.publish --profile skm -- path="${repoPath}" repoType="system_knowledge" message="docs(system): sync domain knowledge and cross-service flows"`,
    `  - 无论文档是否修改，最后必须调用检查点推进动作（绝对交付标志）：`,
    `    - 文档有更新：ad run maintenance/maintenance.complete --profile skm -- path="${repoPath}" commit="${to}" actionTaken="docs_updated" summary="<系统知识更新说明>"`,
    `    - 文档无需更新：ad run maintenance/maintenance.complete --profile skm -- path="${repoPath}" commit="${to}" actionTaken="no_change_needed" summary="<系统级跨仓契约与全局领域未失效，无需更新>"`,
  ];

  return lines.join("\n");
}
